CREATE DATABASE IF NOT EXISTS aprobacion_facturas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE aprobacion_facturas;
CREATE TABLE IF NOT EXISTS proveedores (id BIGINT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS facturas (id BIGINT AUTO_INCREMENT PRIMARY KEY,proveedor_id BIGINT NOT NULL,importe DECIMAL(15,2) NOT NULL,estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',fecha DATETIME NOT NULL,CONSTRAINT fk_factura_proveedor FOREIGN KEY(proveedor_id) REFERENCES proveedores(id),CONSTRAINT chk_estado CHECK(estado IN ('PENDIENTE','APROBADA','RECHAZADA')));
